# This is a basic workflow to help you get started with Actions
name: run-on-schedule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
 schedule:
    - cron: "*/5 * * * *"

jobs:
  job_1:
    name: create backup
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "create backup"
          expr 3 + 7 > test.txt
      - name: Upload backup files to artifact
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test.txt

  job_2:
    name: upload to google drive
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from job_1
        uses: actions/download-artifact@v2
        with:
          name: test
      - shell: bash
        run: |
          value=`cat test.txt`
          echo $value
          echo upload to google drive
