# Regarding limitations: https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

# This is a basic workflow to help you get started with Actions
name: run-on-schedule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
 schedule:
    # - cron: "*/60 */24 */7 * *" # real backup schedule
    - cron "*/5 */14 */ * *"

jobs:
  job_1:
    name: create backup
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "backup: starting""
          npm run backup
          echo "backup: finished"